# Generated by Django 4.1.1 on 2022-09-14 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Listings', '0001_initial'),
        ('Residences', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Swap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Error', 'Error')], default='Pending', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('asker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asker', to=settings.AUTH_USER_MODEL)),
                ('bidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='bidder', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='swap_listing', to='Listings.listing')),
                ('residence_ask', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_ask', to='Residences.residence')),
                ('residence_bid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='residence_bid', to='Residences.residence')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', django_fsm.FSMField(choices=[('Starting', 'Starting'), ('Active', 'Active'), ('Ending', 'Ending'), ('Completed', 'Completed'), ('Voided', 'Voided')], default='Starting', max_length=50)),
                ('days_to_start', models.DateTimeField(blank=True, null=True)),
                ('days_to_end', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('swap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='swap', to='Swaps.swap')),
            ],
        ),
    ]
