# Generated by Django 4.1.1 on 2022-09-14 01:01

import Residences.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('city', models.CharField(blank=True, max_length=25, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=25, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=50, null=True)),
                ('building', models.CharField(blank=True, max_length=25, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('arrangement', models.CharField(blank=True, max_length=25, null=True)),
                ('rooms', models.CharField(blank=True, max_length=25, null=True)),
                ('beds', models.CharField(blank=True, max_length=10, null=True)),
                ('baths', models.CharField(blank=True, max_length=10, null=True)),
                ('sq_ft', models.CharField(blank=True, max_length=25, null=True)),
                ('pets', models.CharField(blank=True, max_length=25, null=True)),
                ('smoking', models.CharField(blank=True, max_length=25, null=True)),
                ('party', models.CharField(blank=True, max_length=25, null=True)),
                ('cleaning', models.CharField(blank=True, max_length=25, null=True)),
                ('linens', models.CharField(blank=True, max_length=25, null=True)),
                ('amenities', models.JSONField(blank=True, default=Residences.models.amenities_default, null=True)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='residences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(null=True, upload_to='')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('default', models.BooleanField(default=False)),
                ('residence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Residences.residence')),
            ],
        ),
    ]
