# Generated by Django 4.1.1 on 2022-09-14 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Residences', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.CharField(blank=True, max_length=25, null=True)),
                ('departure_date', models.CharField(blank=True, max_length=25, null=True)),
                ('arrival_time', models.CharField(blank=True, max_length=25, null=True)),
                ('departure_time', models.CharField(blank=True, max_length=25, null=True)),
                ('duration', models.CharField(blank=True, max_length=25, null=True)),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('residence', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property', to='Residences.residence')),
            ],
        ),
    ]
